#include <bits/stdc++.h>

using namespace std;

int main() {
    printf("WWXKXNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
"WWNKOkk0XWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMWWNWWMMMMMMMMMMMMMM\n"
"WWWWWXOoodOXWWWWWWMWWWWWWWMWWWWMMMMMMMMMMMMMN0kxkOXWMMMMMMMMMMMM\n"
"MWWWWWWXklcld0NWWWWWWWMMMWWWWWMMMMMMMMMMMMMW0xxxxxkXMMMMMMMMMMMM\n"
"WWWMMWWWN0o::coOXWMMWWWWWWMMWWWMMMMMMMMMMMMWN00O00KWMMMMMMMMMMMM\n"
"MWWWWWWMMWKo::::oONWWWMMWWWWWWMMMMMMMMMMXOkkkxxkxxxkkkKWMMMMMMMM\n"
"WWWMMWWWWWW0l;;;;:dXWWWWWWMMWWWMMMMMMMMWOollddlccoxollxNMMMMMMMM\n"
"MWWWWWWMMWWNx:;;;;;o0WMMWWWWWWMMMMMMMMMMOoodKWKO0XWkoodXMMMMMMMM\n"
"WWWMMWWWWWMWOc;;;;;;lKWWWWMMWWWMMMMMMMMMklloXWK00XWkoodXMMMMMMMM\n"
"MWWWWWWMWWWW0c,,,,,,;dNWWWWWWWMMMMMMMMMMklloKWK00XWxoldNMMMMMMMM\n"
"WWWWWWWWWWWWO:,,,,,,,c0WWWWWWWWMMMMMMMMMOllo0WK00XNxlldNMMMMMMMM\n"
"WWWWWWWWWWWNx;,,,,,,,;kWWWWWWWWMMMMMMMMMXdloxKKKKKOoloOWMMMMMMMM\n"
"WWWWWWWWWWWOc,,',,,,';kWWWWWWWWMMMMMMMMMMXkxOOKNX0Okx0WMMMMMMMMM\n"
"WWWWWWWWWW0l,','',,,'c0WWWWWWWWMMMMMMMMMMMWNK0KKK0KXWMMMMMMMMMMM\n"
"WWWWWWWWNOc,'''''''',dNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
"WWWWMWWKd;''''''''''c0WWWWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
"MMWWWW0l,'''''''''';kWMMWWWWWWMMMWWWWMMMWWWWWMMMWWWWWMMMWWWWMMMW\n"
"WWWMWOc,'''''''''',dNWWWWWMMWWWWWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWWW\n"
"MWWW0c'''''''''''':0WWMMWWWWWMMMMWWWWWMMMWWWWNWMWWWWWMMWWWWWWMMW\n"
"WWWXo,''''''''''''oXWWWWWWMMWWWWWWMMMWWWWWWXxd0WWMMMWWWWWMMWWWWW\n"
"MMW0c'''''''''''''oXWWMMWWWWWWWXKXWWWWMWNKxc,lXWWWWWWMMWWWWWWMMW\n"
"WWW0c''''''''''''':OWWWWWWWWN0ddkKWWWWXOo:,,:kNWWWMMWWWWWWWWWWWW\n"
"WMWXl'''''''''''''':kXWWWWXkl,,dXNNX0dc;,,';xNWWWWWWWWWWWNOdOWWW\n"
"WWWWO:'''''''''''''',cxKKkc'..,oOkdc;,'''',dXWWWWWWWWWNKkl;;xWWW\n"
"WWWWNOc'''''''''''''''',;,'',,;::;,'''''',oXWWWWWNX0kdc;,''c0WWW\n"
"WWWWWWXx:'''...'..'''..'',;::;,''........;oxxddol:;,,'''',l0WWWW\n"
"WWWMWWWWXkl;'....'....',;:;,'...................''''''',cxXWWWWW\n"
"WMWWWWWMMWNKko:,'...',,,'...............  .....'''',;cdOXWWWMMWW\n"
"WWWMMWWWWWMMWWX0kdlc;,................   ....',;:ldk0XWWWMMWWWWW\n"
"MMWWWWWMMWWWWWMMMWWNK0OxdooooooooooolllooddddxO0XNWWWMMWWWWWWMMW\n"
"WWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWWMWWWWWWMMWWWWWMMWWWWWWMMMWWWW\n"
"MWWWWWWMMWWWWMMWMWWWWWWWWWWWWWMWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWW\n");
    return 0;
}